name: flutter_chat_desktop
description: "A new Flutter Chat application using MCP and Gemini"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  mcp_dart: ^0.3.6
  google_generative_ai: ^0.4.6
  flutter_riverpod: ^2.0.1
  http: ^1.3.0
  flutter_markdown: ^0.7.7
  shared_preferences: ^2.5.3
  collection: ^1.19.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
